# Analyse Numérique GMM4 - Travaux Pratiques

In [6]:
import numpy as np
import scipy as sp
import scipy.sparse
import scipy.sparse.linalg
import numpy.linalg as npl
import scipy.linalg as spl
import matplotlib.pyplot as plt
#M = np.load("Matrice.npy")

## TP 1 - La méthode de la puissance 

L'objectif de ce TP l'observation du comportement de diverses stratégies 
associées à la méthode de la puissance, ou de la puissance inverse.

On se placera dans le cas ou la matrice $M$ dont on veut calculer une valeur
propre est symétrique.


On va s'intéresser à la méthode de la puissance inverse pour le calcul 
de la plus petite valeur propre d'une matrice $M$  qui vous est fournie, 
dans le fichier Matrice.mat. La matrice $M$ est symétrique 
définie positive. 
Comme nous voulons comparer différentes méthodes, le vecteur initial des 
iterations 
sera un argument des fonctions mettant en oeuvre les différentes méthodes.

#### Les fonctions PinvInf et PinvN2

Créer les fonction PinvInf et PinvN2. La première de ces fonctions mettra en oeuvre l'algorithme de la table 1.1, 
page 13 du polycopié, et la seconde adaptera ce dernier mais dans le cadre d'une norme infinie. 
Pour chaque methode, le test de convergence se fera sur l'écart entre deux itérés successifs de la valeur propre approximée. Le nombre maximum
d'iterations sera limité à deux fois la taille du problème.

In [4]:
def PinvInf(A,x,tol):
    # Arguments en entrée:
    # A : la matrice
    # x : le vecteur initial
    # tol : le seuil de précision de la méthode
    # Arguments en sortie:
    # l : la plus petite valeur propre de la matrice A
    # u : le vecteur propre associé à l
    # Niter : le nombre d'itérations de la méthode
    
    
    return l,u,Niter

In [ ]:
def PinvN2(A,x,tol):
    # Arguments en entrée:
    # A : la matrice
    # x : le vecteur initial
    # tol : le seuil de précision de la méthode
    # Arguments en sortie:
    # l : la plus petite valeur propre de la matrice A
    # u : le vecteur propre associé à l
    # Niter : le nombre d'itérations de la méthode
    
    return l,u,Niter

#### Les fonctions TinvInf et TinvN2

Modifier ces fonctions pour qu'elles mettent en oeuvre une stratégie
de translation-inversion de façon à chercher la valeur propre la plus
proche d'un nombre donné. Vous appelerez ces fonctions TinvInf et TinvN2 ; cette stratégie est décrite à la section 1.2.2, page 17 du polycopié. On ajoutera le paramètre $\sigma $ à la liste des variables en entrée.

In [ ]:
def TinvInf(A,x,sigma,tol):
    # Arguments en entrée:
    # A : la matrice
    # x : le vecteur initial
    # sigma : la valeur du shift
    # tol : le seuil de précision de la méthode
    # Arguments en sortie:
    # l : la valeur propre la plus proche de sigma
    # u : le vecteur propre associé à l
    # Niter : le nombre d'itérations de la méthode
    
    return l,u,Niter

In [ ]:
def TinvN2(A,x,sigma,tol):
    # Arguments en entrée:
    # A : la matrice
    # x : le vecteur initial
    # sigma : la valeur du shift
    # tol : le seuil de précision de la méthode
    # Arguments en sortie:
    # l : la valeur propre la plus proche de sigma
    # u : le vecteur propre associé à l
    # Niter : le nombre d'itérations de la méthode
    
    return l,u,Niter

#### Test de la vitesse de convergence des méthodes

On calcule l'ensemble des valeurs propres de la matrice $M$ à l'aide de la fonction eig de numpy.linalg.

In [ ]:
valP,vecP = npl.eig(M)
valP = sorted(valP,reverse = True)

 Tester la vitesse de convergence vers la 4ème valeur propre selon
$\sigma $, lorsqu'elles sont 
  rangées suivant l'ordre décroissant ; on choisira des valeurs de  de 
la forme 
$ \sigma = \left( \frac{\lambda_4 + \lambda _5}{2} \right) 
 + \frac{i}{10}\, \left( \frac{\lambda_4 - \lambda _5}{2} \right) $, 
$1\leq i \leq 9$.

#### La fonction Rayleigh

Ecrire une fonction Rayleigh qui modifie TinvN2 
suivant l'algorithme du tableau 3.3, page 65 du polycopié.

In [ ]:
def Rayleigh(A,x,tol):
    # Arguments en entrée:
    # A : la matrice
    # x : le vecteur initial
    # tol : le seuil de précision de la méthode
    # Arguments en sortie:
    # l : la valeur propre associée à u
    # u : le vecteur propre le plus proche de x
    # Niter : le nombre d'itérations de la méthode
    
    return l,u,Niter  

Proposez une fonction qui combine PinvN2 et  Rayleigh
pour le calcul de la plus petite valeur propre. Comparez les différentes 
méthodes pour la recherche de la plus petite valeur propre.

#### Calculer plusieurs valeurs propres

###### L'objectif est de calculer $d$ valeurs propres d'une même matrice symétrique, pour cela à l'itération $k$ on effectuera un algorithme de puissance itérée sur $d$ vecteurs en même temps : $(x_1^k,x_2^k,..x_d^k)$. On calcule donc les vecteurs $$y_i^k=A x_i^k \text{ pour } i=1..d.$$ Finalement, comme on sait qu'au final les vecteurs propres de $A$ sont orthogonaux, on orthonormalise les vecteurs $(y_1^k,y_2^k,..y_d^k)$ par un procédé standard de Gram-Schmidt et on prend cette base orthonormalisée comme valeur de $(x_1^{k+1},x_2^{k+1},..x_d^{k+1})$.
On vous donne ci-dessous un procédé de Gram-Schmidt qui prend une suite de vecteurs (mise sous forme de tableau à deux dimensions) et qui l'orthonormalise.

In [129]:
def GramSchmidt(Y) :
    [n,p]=Y.shape
    actual_index=0
    for i in np.arange(p) :
        for j ine de convergence vers la 4ème valeur propre selon 𝜎, lorsqu'elles sont rangées suivant l'ordre décroissant ; on choisira des valeurs de de la forme 𝜎=(𝜆4+𝜆52)+𝑖10(𝜆4−𝜆52), 1≤𝑖≤9

.
 np.arange(i) :
            Y[:,i]-=np.dot(Y[:,i],Y[:,j])*Y[:,j]
        Y[:,i]/=np.linalg.norm(Y[:,i])

A = np.reshape(np.arange(20,dtype=float),(5,4))
print(A)
GramSchmidt(A)
print(A.T.dot(A))

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
[[  1.00000000e+00   4.24660307e-15  -9.35070396e-01  -3.53266657e-01]
 [  4.24660307e-15   1.00000000e+00  -3.47997167e-03   5.25627957e-02]
 [ -9.35070396e-01  -3.47997167e-03   1.00000000e+00  -2.60902411e-15]
 [ -3.53266657e-01   5.25627957e-02  -2.60902411e-15   1.00000000e+00]]


Implémenter un algorithme de calcul des premières valeurs propres. Tester avec la matrice symétrique du Laplacien avec conditions aux bord de Dirichet donné dans la cellule suivante. La formule des premières valeurs propres du Laplacien à $n$ points est :
$$ l[k]=\frac{4}{(n+1)^2}sin^2\left(\frac{k\pi(n+1)}{2}\right)$$

In [131]:
def Laplacian(n) :
    return (n+1)**2*sp.sparse.diags([2*np.ones(n),-1*np.ones(n-1),-1*np.ones(n-1)], [0, -1, 1]).tocsc()
def PinvN2(A,x,tol):
    # Arguments en entrée:
    # A : la matrice
    # x : le vecteur initial (possiblement une matrice)
    # tol : le seuil de précision de la méthode
    # Arguments en sortie:
    # l : les plus petites valeurs propres de la matrice A
    # u : les vecteur propres associé à l
    # Niter : le nombre d'itérations de la méthode
    return l,x,niter

n=500
p=5
x=np.reshape(np.random.rand(n*p),(n,p))
l,x,niter=PinvN2(Laplacian(n),x,1.e-6)

Le laplacien à $n$ points est la matrice de discrétisation de l'opérateur de dérivée seconde sur l'intervalle $[0,1]$. Trouvez tous les $(u,\lambda)$ couples de vecteurs propres et de valeurs propres de l'opérateur Laplacien, c'est-à-dire les fonctions $u$ et les réels $\lambda$ solutions de 
$$\begin{cases} u''(x)=\lambda u(x) \quad \text{sur} [0,1] \\ u(0)=u(1)=0 \end{cases}$$
Comparer avec les vecteurs propres et les valeurs propres de la matrice du Laplacien

Réponse : 